# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PasswordlessClientSdkDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "PromiseKit", "~> 6.13.1"
  pod "EllipticCurveKeyPair", "~> 2.0"
  pod "KeychainAccess", "~> 4.2.1"
  pod "CryptoSwift", "~> 1.3.8"
  pod 'Alamofire'

  # Pods for PasswordlessClientSdkDemo

end


post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.4'
               end
          end
   end
end